"""changed player model

Revision ID: 672c4de1e80d
Revises: 6fabdf2679bf
Create Date: 2022-04-09 14:01:56.495749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672c4de1e80d'
down_revision = '6fabdf2679bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('player', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('player', 'name')
    # ### end Alembic commands ###
